toolbar_location: top
toolbar_align: left
statusbar_location: bottom
buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - image
  - link
  - code
  - fullscreen
  - insertdatetime
  - wordcount
insertdate_dateformat: "%m/%d/%Y"